name: Feature Request
description: Create a feature request for the Web Wallet
labels: ["feature"]
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
    - type: textarea
      attributes:
          label: Describe the feature you'd like to request
          description: A clear and detailed description of what you want.
      validations:
          required: true